// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
float SmoothStep;
float Strength;
float val = 1;

float2 CurrentPosition;
float2 LastPosition;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float2 posCount = LastPosition;
    bool isXTurn = true;
    
    /*while (length(float2(CurrentPosition.x - posCount.x, CurrentPosition.y - posCount.y)) > 0)
    {
        if (isXTurn)
        {
            if (posCount.x != CurrentPosition.x)
            {
                posCount.x += sign(CurrentPosition.x - posCount.x);
                float dist = length(float2(posCount.x - id.x, posCount.y - id.y));
                if (dist < SmoothStep)
                {
                    val = 1; //(SmoothStep - (dist / Strength)) / SmoothStep;
        
                    Result[id.xy] = float4(val, val, val, 1);
                }

            }
            isXTurn = !isXTurn;
        }
        else
        {
            if (posCount.y != CurrentPosition.y)
            {
                posCount.y += sign(CurrentPosition.y - posCount.y);
                float dist = length(float2(posCount.x - id.x, posCount.y - id.y));
                if (dist < SmoothStep)
                {
                    val = 1; //(SmoothStep - (dist / Strength)) / SmoothStep;
        
                    Result[id.xy] = float4(val, val, val, 1);
                }
            }
            isXTurn = !isXTurn;
        }
    }*/
    
    float2 acDist = normalize(id.xy - LastPosition);
    float2 abDist = normalize(CurrentPosition - LastPosition);
    float2 bcDist = normalize(id.xy - CurrentPosition);
    float angle = sqrt(1 - pow(dot(acDist, abDist), 2));
    float dist = length(id.xy - LastPosition) * angle;
    float angle2 = dot(bcDist, abDist);
    float angle3 = dot(acDist, abDist);
    if (dist <= SmoothStep && angle2 <= 0 && angle3 >= 0)
    {
        float len = angle * 10;
        Result[id.xy] = float4(1, 0, 0, 1);
    }
    //Result[id.xy] = float4(dist, dist, dist, 1);
        
}
